"""lazy noload on users.books

Revision ID: 5b26540c8f3c
Revises: 5f1ed03bc7d2
Create Date: 2025-06-24 16:22:47.183721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b26540c8f3c"
down_revision: Union[str, Sequence[str], None] = "5f1ed03bc7d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
