"""lazy select on users.books

Revision ID: 5f1ed03bc7d2
Revises: 09aeacb2dcbb
Create Date: 2025-06-24 16:21:46.472048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f1ed03bc7d2"
down_revision: Union[str, Sequence[str], None] = "09aeacb2dcbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
